sdxl pipeline load workaround
For some strange reason I get the error

safetensors_rust.SafetensorError: device cuda:0 is invalid

when calling unet.load_state_dict. But if I cast the device
to a string, then everything is fine. So this is a workaround.